server:
  port: 8085
  servlet:
    context-path: /api/flashcards
spring:
  application:
    name: flashcard-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alp_flashcards}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: health, info
